version: '3.8'

services:
  rizzume_inference:
    build: .
    image: rizzume_inference
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - rizzume_network
    volumes:
      - ./inference:/usr/local/app/inference  # Mount inference folder for hot-reloading

  ollama:
    container_name: ollama
    image: ollama/ollama:rocm
    restart: always
    ports:
      - "11434:11434"
    networks:
      - rizzume_network
    volumes:
      - ollama:/root/.ollama
    devices:
      - /dev/kfd
      - /dev/dri
    command: ["ollama", "serve"]

networks:
  rizzume_network:
    driver: bridge

volumes:
  ollama:
